name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      # - name: Run tests
      #   run: npm run test
      #   env:
      #     CI: "true"
      - name: Build project
        run: npm run build
      - name: Upload Installer Asset
        id: upload-installer-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: lib/index.js
          asset_name: index.js
          asset_content_type: application/javascript
